# Generated by Django 5.2.5 on 2025-09-04 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MDCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分类代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'MD分类',
                'verbose_name_plural': 'MD分类',
                'db_table': 'md_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MDDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(choices=[('spirit', '精神'), ('person', '人物'), ('party_history', '党史')], max_length=20, verbose_name='类别')),
                ('content', models.TextField(verbose_name='MD内容')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('source', models.CharField(blank=True, max_length=200, null=True, verbose_name='来源')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='发布日期')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('image_count', models.IntegerField(default=0, verbose_name='图片数量')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'MD文档',
                'verbose_name_plural': 'MD文档',
                'db_table': 'md_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='md_document_categor_a830e7_idx'), models.Index(fields=['is_published'], name='md_document_is_publ_414c16_idx'), models.Index(fields=['created_at'], name='md_document_created_d815ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='MDImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('stored_filename', models.CharField(max_length=255, verbose_name='存储文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('content_type', models.CharField(max_length=100, verbose_name='内容类型')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='替代文本')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='md_docs.mddocument', verbose_name='所属文档')),
            ],
            options={
                'verbose_name': 'MD图片',
                'verbose_name_plural': 'MD图片',
                'db_table': 'md_images',
                'ordering': ['upload_time'],
            },
        ),
    ]
