# Generated by Django 5.2.5 on 2025-09-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('md_docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdimage',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='md_docs.mddocument', verbose_name='所属文档'),
        ),
    ]
