# Generated by Django 5.2.5 on 2025-09-02 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='输入文本')),
                ('voice', models.CharField(default='zh-CN-XiaoxiaoNeural', max_length=50, verbose_name='语音类型')),
                ('language', models.CharField(default='zh-CN', max_length=10, verbose_name='语言')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('audio_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='音频文件路径')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='音频时长(秒)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': 'TTS请求',
                'verbose_name_plural': 'TTS请求',
                'db_table': 'tts_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
