# Generated by Django 5.2.5 on 2025-09-01 01:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('target_url', models.URLField(verbose_name='目标URL')),
                ('task_type', models.CharField(choices=[('list', '列表页爬取'), ('detail', '详情页爬取'), ('full', '完整爬取')], default='full', max_length=20, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='任务状态')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('total_links', models.IntegerField(default=0, verbose_name='总链接数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数量')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数量')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '爬取任务',
                'verbose_name_plural': '爬取任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('url', models.URLField(unique=True, verbose_name='原文链接')),
                ('source', models.CharField(max_length=100, verbose_name='来源')),
                ('publish_date', models.DateTimeField(verbose_name='发布时间')),
                ('content', models.TextField(verbose_name='正文内容')),
                ('markdown_content', models.TextField(verbose_name='Markdown格式内容')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('tags', models.CharField(blank=True, max_length=200, verbose_name='标签')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('crawl_status', models.CharField(choices=[('pending', '待处理'), ('crawling', '爬取中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='爬取状态')),
                ('view_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('image_count', models.IntegerField(default=0, verbose_name='图片数量')),
            ],
            options={
                'verbose_name': '新闻文章',
                'verbose_name_plural': '新闻文章',
                'ordering': ['-publish_date'],
                'indexes': [models.Index(fields=['publish_date'], name='crawler_new_publish_a8cc0a_idx'), models.Index(fields=['source'], name='crawler_new_source_811c8e_idx'), models.Index(fields=['category'], name='crawler_new_categor_27f08c_idx'), models.Index(fields=['crawl_status'], name='crawler_new_crawl_s_3d8ed8_idx')],
            },
        ),
    ]
