# Generated by Django 5.2.5 on 2025-09-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrawlTask',
        ),
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
