# Generated by Django 5.2.5 on 2025-09-07 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='问题内容')),
                ('question_type', models.CharField(choices=[('comprehension', '理解型'), ('application', '应用型'), ('analysis', '分析型'), ('evaluation', '评价型'), ('creation', '创造型')], default='comprehension', max_length=20, verbose_name='问题类型')),
                ('difficulty_level', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=10, verbose_name='难度等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_questions', to='knowledge_quiz.knowledge', verbose_name='关联知识')),
            ],
            options={
                'verbose_name': '开放性提问',
                'verbose_name_plural': '开放性提问',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('choice_explanation', '选择题详细解答'), ('fill_explanation', '填空题详细解答'), ('open_question_generation', '开放性提问生成'), ('answer_relevance_analysis', '回答相关度分析')], max_length=30, verbose_name='分析类型')),
                ('analysis_content', models.TextField(verbose_name='分析内容')),
                ('ai_model_used', models.CharField(max_length=100, verbose_name='使用的AI模型')),
                ('tokens_used', models.IntegerField(blank=True, null=True, verbose_name='使用的Token数')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('open_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='knowledge_ai.openquestion', verbose_name='开放性问题')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='knowledge_quiz.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目AI分析',
                'verbose_name_plural': '题目AI分析',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='用户回答')),
                ('relevance_score', models.IntegerField(blank=True, help_text='0-100分，表示回答与知识点的相关度', null=True, verbose_name='相关度评分')),
                ('feedback_text', models.TextField(blank=True, help_text='AI生成的详细反馈', verbose_name='反馈文本')),
                ('analysis_metadata', models.JSONField(blank=True, default=dict, help_text='存储分析过程中的额外信息', verbose_name='分析元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回答时间')),
                ('open_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='knowledge_ai.openquestion', verbose_name='关联问题')),
            ],
            options={
                'verbose_name': '用户回答',
                'verbose_name_plural': '用户回答',
                'ordering': ['-created_at'],
            },
        ),
    ]
