# Generated by Django 5.2.5 on 2025-09-04 02:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.CharField(choices=[('general', '通用知识'), ('technology', '技术'), ('science', '科学'), ('history', '历史'), ('literature', '文学'), ('math', '数学'), ('language', '语言'), ('other', '其他')], default='general', max_length=20, verbose_name='分类')),
                ('tags', models.CharField(blank=True, help_text='用逗号分隔多个标签', max_length=500, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知识条目',
                'verbose_name_plural': '知识条目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='会话ID')),
                ('total_questions', models.IntegerField(default=0, verbose_name='总题数')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='正确题数')),
                ('score', models.FloatField(default=0.0, verbose_name='得分')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '答题会话',
                'verbose_name_plural': '答题会话',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='题目内容')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('true_false', '判断题'), ('fill_blank', '填空题'), ('short_answer', '简答题')], max_length=20, verbose_name='题目类型')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=10, verbose_name='难度')),
                ('options', models.JSONField(blank=True, default=list, help_text='JSON格式的选项列表', verbose_name='选项')),
                ('correct_answer', models.TextField(verbose_name='正确答案')),
                ('explanation', models.TextField(blank=True, verbose_name='答案解析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='knowledge_quiz.knowledge', verbose_name='关联知识')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='用户答案')),
                ('is_correct', models.BooleanField(verbose_name='是否正确')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='答题时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='knowledge_quiz.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
                'ordering': ['-answered_at'],
            },
        ),
    ]
