# Generated by Django 5.2.5 on 2025-09-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='category',
            field=models.CharField(choices=[('marxism_leninism', '马克思列宁主义'), ('mao_zedong_thought', '毛泽东思想'), ('deng_xiaoping_theory', '邓小平理论'), ('three_represents', '"三个代表"重要思想'), ('scientific_development', '科学发展观'), ('xi_jinping_thought', '习近平新时代中国特色社会主义思想')], default='marxism_leninism', max_length=30, verbose_name='分类'),
        ),
    ]
