# Generated by Django 5.2.5 on 2025-09-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='FillQuestion',
        ),
    ]
