# Generated by Django 5.2.5 on 2025-09-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_quiz', '0002_alter_knowledge_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge',
            name='source',
            field=models.CharField(default='共产党员网', help_text='知识条目的来源网站或机构', max_length=100, verbose_name='数据来源'),
        ),
    ]
