# Generated by Django 5.2.5 on 2025-09-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_quiz', '0003_knowledge_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='knowledge',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('marxism_leninism', '马克思列宁主义'), ('mao_zedong_thought', '毛泽东思想'), ('deng_xiaoping_theory', '邓小平理论'), ('three_represents', '"三个代表"重要思想'), ('scientific_development', '科学发展观'), ('xi_jinping_thought', '习近平新时代中国特色社会主义思想')], default='marxism_leninism', max_length=30, verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, help_text='用逗号分隔多个标签', max_length=500, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='选择题的选项列表，格式：[{"text": "选项内容", "is_correct": true}]', verbose_name='选项'),
        ),
    ]
