# Generated by Django 5.2.5 on 2025-09-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_quiz', '0004_remove_question_knowledge_question_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('party_history', '党史'), ('theory', '理论')], default='party_history', max_length=20, verbose_name='分类'),
        ),
    ]
