# Generated by Django 5.2.5 on 2025-09-04 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_quiz', '0005_alter_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='题目内容')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=10, verbose_name='难度')),
                ('category', models.CharField(choices=[('party_history', '党史'), ('theory', '理论')], default='party_history', max_length=20, verbose_name='分类')),
                ('explanation', models.TextField(blank=True, verbose_name='答案解析')),
                ('tags', models.CharField(blank=True, help_text='用逗号分隔多个标签', max_length=500, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题')], max_length=20, verbose_name='题目类型')),
                ('options', models.JSONField(default=list, help_text='选择题的选项列表，格式：[{"text": "选项内容", "is_correct": true}]', verbose_name='选项')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FillQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='题目内容')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=10, verbose_name='难度')),
                ('category', models.CharField(choices=[('party_history', '党史'), ('theory', '理论')], default='party_history', max_length=20, verbose_name='分类')),
                ('explanation', models.TextField(blank=True, verbose_name='答案解析')),
                ('tags', models.CharField(blank=True, help_text='用逗号分隔多个标签', max_length=500, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('correct_answer', models.TextField(help_text='填空题的正确答案，多个答案用分号分隔', verbose_name='正确答案')),
            ],
            options={
                'verbose_name': '填空题',
                'verbose_name_plural': '填空题',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_type',
            field=models.CharField(choices=[('choice', '选择题'), ('fill', '填空题')], default='choice', max_length=10, verbose_name='题目类型'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='knowledge_quiz.choicequestion', verbose_name='选择题'),
        ),
        migrations.AddField(
            model_name='answer',
            name='fill_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='knowledge_quiz.fillquestion', verbose_name='填空题'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
