# Generated by Django 5.2.5 on 2025-09-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_quiz', '0006_separate_question_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.GenericIPAddressField(verbose_name='客户端IP')),
                ('question_type', models.CharField(choices=[('choice', '选择题'), ('fill', '填空题')], max_length=10, verbose_name='题目类型')),
                ('question_id', models.IntegerField(verbose_name='题目ID')),
                ('question_data', models.JSONField(help_text='包含题目、选项和正确答案的完整数据', verbose_name='题目数据')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '每日一题记录',
                'verbose_name_plural': '每日一题记录',
                'ordering': ['-created_at'],
                'unique_together': {('client_ip', 'date')},
            },
        ),
    ]
